# Generated by Django 5.1.6 on 2026-03-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_connect', '0002_event_created_at_event_image_event_registration_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_audience',
        ),
    ]
