# Generated by Django 5.1.6 on 2026-03-16 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_connect', '0003_remove_event_created_at_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(default='All Students', help_text='e.g., All College Students, CSE Dept Only, External Participants', max_length=150),
        ),
    ]
