# Generated by Django 5.1.6 on 2026-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_connect', '0005_event_host_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
