# Generated by Django 5.1.6 on 2026-03-17 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_connect', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=models.FileField(default=None, upload_to='brochures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
